# Generated by Django 6.0.5 on 2026-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_type', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
