# Generated by Django 6.0.5 on 2026-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
